/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>
#define SET_BIT(ADDRESS, BIT) ADDRESS |= (1<<BIT)
#define RESET_BIT(ADDRESS, BIT) ADDRESS &= ~(1<<BIT)
#define TOGGLE_BIT(ADDRESS, BIT) ADDRESS ^= (1<<BIT)
#define READ_BIT(ADDRESS, BIT) ((ADDRESS & (1<<BIT))>>BIT)
typedef volatile unsigned int vuint32_t;

// RCC Register Address
#define RCC_BASE	0x40021000
#define RCC_APB2ENR *(vuint32_t *)(RCC_BASE +0x18)

// GPIOA Register Address
#define GPIOA_BASE	0x40010800
#define GPIOA_CRl   *(vuint32_t *)(GPIOA_BASE +0x00)
#define GPIOA_CRH   *(vuint32_t *)(GPIOA_BASE +0x04)
#define GPIOA_IDR   *(vuint32_t *)(GPIOA_BASE +0x08)
#define GPIOA_ODR   *(vuint32_t *)(GPIOA_BASE +0x0C)


// GPIOB Register Address
#define GPIOB_BASE	0x40010C00
#define GPIOB_CRl   *(vuint32_t *)(GPIOB_BASE +0x00)
#define GPIOB_CRH   *(vuint32_t *)(GPIOB_BASE +0x04)
#define GPIOB_IDR   *(vuint32_t *)(GPIOB_BASE +0x08)
#define GPIOB_ODR   *(vuint32_t *)(GPIOB_BASE +0x0C)

void Clock_Init(){
	//	enable clock for IO port A
	SET_BIT(RCC_APB2ENR,2);
	//	enable clock for IO port B
	SET_BIT(RCC_APB2ENR,3);

}
void GPIO_Init(){

	//pin 1 portA floating input with pull up
	SET_BIT(GPIOA_CRl,6);
	RESET_BIT(GPIOA_CRl,4);
	RESET_BIT(GPIOA_CRl,5);

	//pin 1 portB output push pull
	SET_BIT(GPIOB_CRl,4);
	RESET_BIT(GPIOB_CRl,6);
	RESET_BIT(GPIOB_CRl,7);

	//pin 13 portA floating input with pull down
	SET_BIT(GPIOA_CRH,22);
	RESET_BIT(GPIOA_CRH,20);
	RESET_BIT(GPIOA_CRH,21);

	//pin 13 portB output push pull
	SET_BIT(GPIOB_CRH,20);
	RESET_BIT(GPIOB_CRH,22);
	RESET_BIT(GPIOB_CRH,23);
}
void wait(int x){
	int i,j;
	for(i=0 ; i < x ; i++){
		for(j=0 ; j < 255 ;j++);
	}
}
int main(void)
{
	Clock_Init();
	GPIO_Init();
	while(1){
		if(( ( GPIOA_IDR &(1<<1) ) >> 1) == 0 ){
			GPIOB_ODR ^= 1<<1 ;
			while( ((( GPIOA_IDR & (1<<1)) >>1 ) == 0) );
		}

		if(( ( GPIOA_IDR &(1<<13) ) >> 13) == 1 ){
			GPIOB_ODR ^= 1<<13 ;
		}

		wait(10);
	}
	return 0;
}

