/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */
#include <stdint.h>
#define SET_BIT(ADDRESS, BIT) ADDRESS |= (1<<BIT)
#define RESET_BIT(ADDRESS, BIT) ADDRESS &= ~(1<<BIT)
#define TOGGLE_BIT(ADDRESS, BIT) ADDRESS ^= (1<<BIT)
#define READ_BIT(ADDRESS, BIT) ((ADDRESS & (1<<BIT))>>BIT)
typedef volatile unsigned int vuint32_t;

// RCC Register Address
#define RCC_BASE	0x40021000
#define RCC_APB2ENR *(vuint32_t *)(RCC_BASE +0x18)

// GPIO Register Address
#define GPIOA_BASE	0x40010800
#define GPIOA_CRl   *(vuint32_t *)(GPIOA_BASE +0x00)
#define GPIOA_CRH   *(vuint32_t *)(GPIOA_BASE +0x04)
#define GPIOA_ODR   *(vuint32_t *)(GPIOA_BASE +0x0C)

//	AFIO Register Address
#define AFIO_BASE	0x40010000
#define AFIO_EXTICR1   *(vuint32_t *)(AFIO_BASE +0x08)

// INTI register Address
#define INTI_BASE	0x40010400
#define EXTI_IMR   *(vuint32_t *)(INTI_BASE +0x00)
#define EXTI_RTSR   *(vuint32_t *)(INTI_BASE +0x08)
#define EXTI_PR   *(vuint32_t *)(INTI_BASE +0x14)

//	NVIC Register Address
#define NVIC_BASE	0xE000E100
#define NVIC_EXTIE0  *(vuint32_t *)(NVIC_BASE +0x00)

void Clock_Init(){
	//	enable clock for AFIO & IO
	SET_BIT(RCC_APB2ENR,0);
	SET_BIT(RCC_APB2ENR,2);
}
void GPIO_Init(){
	//	pin 13 portA output
	GPIOA_CRH &= 0xFF0FFFFF;
	GPIOA_CRH |= 0x00200000;
	//	pin 0 portA floating input
	SET_BIT(GPIOA_CRl,2);
}
void AFIO_Init(){
	//	config EXTI0 to portA
	AFIO_EXTICR1 = 0x0;
}
void EXTI_Init(){
	//	enable mask INTI line 0
	SET_BIT(EXTI_IMR,0);
	// 	enable raising trigger
	SET_BIT(EXTI_RTSR,0);
}
void NVIC_Init(){
	//	enable NVIC IRQ6 to INTI0
	SET_BIT(NVIC_EXTIE0,6);
}


int main(void)
{
	Clock_Init();
	GPIO_Init();
	AFIO_Init();
	EXTI_Init();
	NVIC_Init();
	while(1);

	return 0;
}

void EXTI0_IRQHandler(){
	//	toggle pin 13 portA
	TOGGLE_BIT(GPIOA_ODR,13);
	//	reset pending request line 0
	SET_BIT(EXTI_PR,0);
}

