/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


#include "stm32f103x6.h"
#include "stm32f103c6_gpio_driver.h"
#include "stm32f103c6_EXTI_driver.h"
#include "Keypad.h"
#include "LCD.h"



unsigned int IRQ_Flag = 0;

void wait(int x){
	int i,j;
	for(i=0 ; i < x ; i++){
		for(j=0 ; j < 255 ;j++);
	}
}


void EXTI9_Callback(void){
	IRQ_Flag = 1;
	LCD_write_string("IRQ EXTI is happened _|- ");
	wait(1000);
}

int main(void)
{

	RCC_EN_CLK_GPIOA();
	RCC_EN_CLK_GPIOB();
	RCC_EN_CLK_AFIO();


	LCD_init();
	LCD_clear_screen();

	EXTI_PinConfig_t EXTI_CFG;
	EXTI_CFG.EXTI_PIN = EXTI9PB9;
	EXTI_CFG.Trigger_Case = EXTI_Trigger_RISING;
	EXTI_CFG.P_IRQ_CallBack = EXTI9_Callback;
	EXTI_CFG.IRQ_EN=EXTI_IRQ_Enable;

	MCAL_EXTI_GPIO_Init(&EXTI_CFG);


	IRQ_Flag = 1;
	while(1){
		if(IRQ_Flag == 1){
			LCD_clear_screen();
		}
	}



}
