/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "stm32f103x6.h"
#include "stm32f103c6_EXTI_driver.h"
#include "stm32f103c6_gpio_driver.h"
#include "stm32f103c6_USART_driver.h"

void clock_init(){
	RCC_EN_CLK_GPIOA();
	RCC_EN_CLK_GPIOB();
	RCC_EN_CLK_AFIO();
}

unsigned ch;

//void UART_IRQ_Callback(void){
//	MCAL_USART_ReceiveData(USART1, &ch, disable);
//	MCAL_USART_SendData(USART1, &ch, enable);
//
//
//}

int main(void){

	USART_Config_t uartCFG;

	clock_init();

	uartCFG.BaudRate = USART_BaudRate_115200;
	uartCFG.HwFlowCtl = USART_HwFlowCtl_NONE;
	uartCFG.IRQ_EN = USART_IRQ_EN_NONE;
	uartCFG.P_IRQ_CallBack = NULL;
	uartCFG.Parity = USART_Parity_NONE;
	uartCFG.Payload_Length = USART_Payload_Length_8B;
	uartCFG.StopBits = USART_StopBits_1;
	uartCFG.USART_Mode = USART_Mode_Tx_RX;

	MCAL_USART_Init(USART1, &uartCFG);
	MCAL_USART_GPIO_Set_Pins(USART1);


	while(1){
		MCAL_USART_ReceiveData(USART1, &ch, enable);
		MCAL_USART_SendData(USART1, &ch, enable);

	}

}



