#bolis
CC=arm-none-eabi-
CFLAGS=-g -mcpu=arm926ej-s
INCS=-I .
LIBS=
SRC = $(wildcard *.c)
OBJ = $(SRC:.c=.o)
AS = $(wildcard *.s)
ASOBJ =$(AS:.s=.o)
Project_name=App
all: ${Project_name}.bin
	@echo "Build Is Done >>>>>>>>>>>>>>>>>>"

startup.o: startup.s
	${CC}as.exe ${CFLAGS} $< -o $@

%.o: %.c
	${CC}gcc.exe -c ${CFLAGS} ${INCS} $< -o $@

${Project_name}.elf: ${ASOBJ} ${OBJ}
	${CC}ld.exe -T Linker_Script.ld ${LIBS} ${OBJ} ${ASOBJ} -o $@	

${Project_name}.bin: App.elf	
	${CC}objcopy.exe -O binary $< $@

clean-all:
	rm *.o *.elf *.bin
	@echo "Everything clean"

clean:
	rm *.elf *.bin