#bolis Karam
CC=arm-none-eabi-
CFLAGS= -mcpu=cortex-m4 -gdwarf-2 -g
INCS=-I .
LIBS=
SRC = $(wildcard *.c)
OBJ = $(SRC:.c=.o)
AS = $(wildcard *.s)
ASOBJ =$(AS:.s=.o)
Project_name = App_cortex_m4

all: ${Project_name}.bin
	@echo "Build Is Done >>>>>>>>>>>>>>>>>>"

# startup.o: startup.s
# 	${CC}as.exe ${CFLAGS} $< -o $@

%.o: %.c
	${CC}gcc.exe -c -mthumb -std=c99 ${CFLAGS} ${INCS} $< -o $@

${Project_name}.elf: ${ASOBJ} ${OBJ}
	${CC}ld.exe -T linker_script.ld ${LIBS} -Map=map_file.map ${OBJ} ${ASOBJ} -o $@
	cp ${Project_name}.elf $(Project_name).axf
	
${Project_name}.bin: ${Project_name}.elf	
	${CC}objcopy.exe -O binary $< $@

clean-all:
	rm *.o *.elf *.bin
	@echo "Everything clean"

clean:
	rm *.elf *.bin